### ISSUE TITLE
Fail to invoke patchelf

### ISSUE THREAD

**Issue by mengrj** [FuzzAnything/Hopper#12]
Thanks for providing this interesting tool! 

While using it, I encountered the following issue. How should I solve it? 

```
07:58:58 [INFO] patchelf cmd: "/hopper/install", lib_name: "libcjson_fuzz.so", path: /hopper/install/output/libcjson_fuzz.so
07:58:58 [ERROR] Meets error: Fail to invoke patchelf
Error: Fail to invoke patchelf

Caused by:
    Permission denied (os error 13)

Location:
    hopper-compiler/src/patch/patchelf.rs:31:10
```

**Comment by spinpx** [comment]
Hi, @mengrj , thanks for your feedback. Could your check that if patchelf is in the path or not ?   The might not  be downloaded successfully or something error. if it is try run build.sh again, and report the error for us.

Alsos, could you provide your environment information ? e.g OS, rust version, clang version ..

**Comment by mengrj** [comment]
Thanks for your response! I rebuilt it and it works now.
