### ISSUE TITLE
请问该库是否只支持 library API?

### ISSUE THREAD

**Issue by Taolaw** [FuzzAnything/hopper#3]
作者您好：
    根据您开放的案例来看目前此项目只适用于对library API的情况，请问对于其他二进制可执行文件的API是否可用，谢谢！

**Comment by yuxuan-xie** [comment]
Hopper currently takes C/C++ header files and the corresponding shared libraries as inputs. The test targets are all from those functions defined in the header files. If you do want to test an executable file and are willing to get your hands dirty. Maybe you can transform a PIE ELF executable into a library through approaches like 
https://lief-project.github.io/doc/latest/tutorials/08_elf_bin2lib.html. 
But remember, Hopper's instrumentation ability only supports ELF files for now.
