### ISSUE TITLE
How to set some arg to mutable string type in rule file 

### ISSUE THREAD

**Issue by tianstcht** [FuzzAnything/Hopper#7]

**Comment by spinpx** [comment]
Hopper  parses the argument's type from  definitions automatically. If it is a string (e.g char*), it will generate a string and mutate it.

Do you mean to set something like `void*` type to be a string??

**Comment by tianstcht** [comment]
Thanks to your reply, It looks like I misunderstood somthing, and solved by automatical hopper.
