### ISSUE TITLE
i got a new bug about 'struct'

### ISSUE THREAD

**Issue by 0xfocu5** [FuzzAnything/Hopper#8]
I have defined a structure like this

typedef struct test {
    struct test *next;
} test_t;

when i translated id_000000 i got a wrong c  code file：

int main() {
    test *v0_tmp[] = {NULL, }; // list
    ....
}

it used `test` not `test_t` or `struct test`

**Comment by yuxuan-xie** [comment]
This problem is supposed to be handled with https://github.com/FuzzAnything/Hopper/blob/main/hopper-harness/src/bin/hopper-translate.rs#L48C4-L48C13. Can you provide the detailed output of hopper-translate?
