### ISSUE TITLE
how to solve this compiler error?

### ISSUE THREAD

**Issue by Arashimu** [FuzzAnything/Hopper#9]
work environment: Ubuntu22.10  gcc-12.0.1 cargo-1.74
when I run build.sh, it shows me an error as follow:

``` shell
gcc hopper-e9-rt.o -o hopper-e9-rt -pie -nostdlib -Wl,-z -Wl,max-page-size=4096 -Wl,-z -Wl,norelro -Wl,-z -Wl,stack-size=0 -Wl,--export-dynamic -Wl,--entry=0x0 -Wl,--strip-all
/usr/bin/ld: hopper-e9-rt.o: in function `e9_vsnprintf':
hopper-e9-rt.c:(.text+0xaef): undefined reference to `strlen'
/usr/bin/ld: hopper-e9-rt.o: in function `print_message':
hopper-e9-rt.c:(.text+0x12bd): undefined reference to `strlen'
collect2: error: ld returned 1 exit status

error: linking (hopper-e9-rt) failed 
```

how could I solve it?

**Comment by GJDuck** [comment]
I think the `strlen` error is fixed in the latest version of E9Patch.  Otherwise, please report E9Patch bugs here: https://github.com/GJDuck/e9patch/issues

**Comment by Arashimu** [comment]
> I think the `strlen` error is fixed in the latest version of E9Patch. Otherwise, please report E9Patch bugs here: https://github.com/GJDuck/e9patch/issues

Yes,I replace the version of e9patch and it work successfully finally!
